name: Firewall Rule Validation and Conversion

on:
  pull_request:
    types: [opened]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Validate Firewall Rules CSV
        uses: drewpypro/drewpy-actions/.github/rule_validation@main
        with:
          input-file: firewall_rules.csv

  convert:
    needs: validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} 

      - name: Convert Firewall Rules CSV to JSON
        uses: drewpypro/drewpy-actions/.github/rule_conversion@main
        with:
          input-file: firewall_rules.csv
      
      - name: Commit JSON Changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add sg_rules/*.json rule_count.txt
          git commit -m "Update JSON rules after CSV conversion" || echo "No changes to commit"
          git push
