name: terraform destroy workflow

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_KEY: ${{ secrets.BUCKET_KEY }}
  BUCKET_ENDPOINT: ${{ secrets.BUCKET_ENDPOINT }}
  BUCKET_ACCESS_KEY_ID: ${{ secrets.BUCKET_ACCESS_KEY_ID }}
  BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: terraform init
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=$BUCKET_KEY" \
            -backend-config="endpoint=$BUCKET_ENDPOINT" \
            -backend-config="access_key=$BUCKET_ACCESS_KEY_ID" \
            -backend-config="secret_key=$BUCKET_SECRET_ACCESS_KEY"
      - name: terraform destroy
        run: |
          terraform destroy -auto-approve